version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/user-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gradle"
    directory: "/gateway"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gradle"
    directory: "/discoveryclient"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gradle"
    directory: "/configserver"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/product-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/payment-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
