spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      routes:
        - id: user-service
          url: lb://user-service
          predicates:
            - Path=/api/v1/users/**
