spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/project/mini-ecommerce-microservices/configrepo
  security:
    user:
      name: config
      password: secret

server:
  port: 8888
