spring:
  application:
    name: user-service
  config:
    import: optional:config-server:http://localhost:8888
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:asdf}
    password: ${DB_PASSWORD:asdf}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-in-ms: ${JWT_EXPIRATION_IN_MS}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/